### ISSUE TITLE
YAML error: EOF while parsing a value

### ISSUE THREAD

**Issue by hawkoon** [sethierophant/longboard#10]
Entering the command `longctl add-staff -r administrator -u NAME -p PASSWORD` throws the error mentioned above. The longboard service also won't start because of the same error.

**Comment by hawkoon** [comment]
Executing just 'longctl' or 'longboard' without anything after it also throws the error btw.

**Comment by sethierophant** [comment]
You can uncomment any line in your config file to fix this.

I think this is a bug in serde_yaml, I will need to do some more research though.

**Comment by sethierophant** [comment]
BTW if you didn't change any of the install options the config file should be at `/usr/local/etc/longboard/config.yaml`.

**Comment by sethierophant** [comment]
Yeah this is caused by https://github.com/dtolnay/serde-yaml/issues/86
