### ISSUE TITLE
Install fails during make

### ISSUE THREAD

**Issue by hawkoon** [sethierophant/longboard#9]
```
   Compiling devise_core v0.2.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_diagnostic, proc_macro_span)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:2:1
  |
2 | #![feature(crate_visibility_modifier)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devise_core-0.2.0/src/lib.rs:3:1
  |
3 | #![feature(concat_idents)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: could not compile `devise_core`.

To learn more, run the command again with --verbose.
make: *** [target/release/longboard] Error 101

```

**Comment by hawkoon** [comment]
rustc --explain E0554 gave this:

```

Feature attributes are only allowed on the nightly release channel. Stable or
beta compilers will not comply.

Example of erroneous code (on a stable compiler):

```
#![feature(non_ascii_idents)] // error: `#![feature]` may not be used on the
                              //        stable release channel
```

If you need the feature, make sure to use a nightly release of the compiler
(but be warned that the feature may be removed or altered in the future).
```

**Comment by sethierophant** [comment]
Sorry for the delay!

You need a nightly compiler to compile this project because I use some nightly features, and also because some of the dependencies like `derive_more` and `rocket` use nightly features.

If you installed Rust with rustup, run `rustup default nightly` to switch to the nightly compiler.

Please let me know if you have any other problems! I've been doing a lot of debugging on the build process and the Makefile after actually deploying it to a VPS but I'm sure there are things I've missed.

**Comment by sethierophant** [comment]
Also, I changed the Makefile  to always use a nightly compiler in 9e8a492d23192370651b1e5df14bef2de0b2c003. Hopefully this will make it easier for people to build from source even if they don't know anything about Rust compiler versions.

**Comment by hawkoon** [comment]
Using rustc 1.45.0-nightly (0aa6751c1 2020-05-20) I now get this error:

> error: linker `cc` not found
>   |
>   = note: No such file or directory (os error 2)
> 
> error: aborting due to previous error
> 
> error: could not compile `libc`.

**Comment by hawkoon** [comment]
New error:

>   = note: /usr/bin/ld: cannot find -lpq
>           collect2: error: ld returned 1 exit status
> 
> 
> error: aborting due to previous error
> 
> error: could not compile `migrations_macros`.

**Comment by sethierophant** [comment]
Added some more info to the README in 2e72cdc. Thanks for the feeback!
